monolog:
  handlers:
    # this "file_log" key could be anything
    file_log:
      type: stream
      # log to var/log/(environment).log
      path: "%kernel.logs_dir%/%kernel.environment%.log"
      # log *all* messages (debug is lowest level)
      level: debug

    syslog_handler:
      type: syslog
      # log error-level messages and higher
      level: error
    es:
      type: service
      id: Symfony\Bridge\Monolog\Handler\ElasticsearchLogstashHandler